CREATE TABLE IF NOT EXISTS watchlist_movies (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tmdb_id INT UNSIGNED NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    release_date DATE NULL,
    release_year CHAR(4) NULL,
    poster_path VARCHAR(255) NULL,
    overview TEXT NULL,
    vote_average DECIMAL(3,1) NULL,
    watched TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
